repos:
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-added-large-files
        args: ['--maxkb=100']
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: ['flake8-no-implicit-concat']
        args:
        - -j4
        exclude: '^vmvo/utils/pyslam/'
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ['--init-hook=import sys; sys.path.append("./")', '--extension-pkg-whitelist=cv2']
        exclude: '^vmvo/utils/pyslam/'
